# Autogenerated wrapper script for libtasn1_jll for i686-w64-mingw32
export asn1Coding, asn1Decoding, asn1Parser, libtasn1

JLLWrappers.@generate_wrapper_header("libtasn1")
JLLWrappers.@declare_library_product(libtasn1, "libtasn1-6.dll")
JLLWrappers.@declare_executable_product(asn1Coding)
JLLWrappers.@declare_executable_product(asn1Decoding)
JLLWrappers.@declare_executable_product(asn1Parser)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtasn1,
        "bin\\libtasn1-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        asn1Coding,
        "bin\\asn1Coding.exe",
    )

    JLLWrappers.@init_executable_product(
        asn1Decoding,
        "bin\\asn1Decoding.exe",
    )

    JLLWrappers.@init_executable_product(
        asn1Parser,
        "bin\\asn1Parser.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
